app/models/user.py
from flask import current_app
from sqlalchemy.orm import Mapped, mapped_column, relationship
from flask_login import UserMixin
from app import db



class Blog_User(UserMixin, db.Model):
    __tablename__ = "blog_user"
    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    email: Mapped[str] = mapped_column(db.String(80), nullable=False)
    username: Mapped[str] = mapped_column(db.String(80), nullable=False)
    password: Mapped[str] = mapped_column(db.String(120), nullable=False)

    post: Mapped[list["Blog_Post"]] = relationship("Blog_Post", back_populates="user", cascade="all, delete-orphan")

    def get_id(self):
        return str(self.id)

    def __repr__(self):
        return f"<User: {self.id} {self.email}>"

app/forms/login.py
from flask_wtf import FlaskForm
from wtforms import EmailField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Length

class LoginForm(FlaskForm):
    email = EmailField("Email", validators=[DataRequired()])
    password = PasswordField("Password", validators=[DataRequired(), Length(min=8, max=20)])
    submit = SubmitField('Submit')

app/forms/sign_up.py
from flask_wtf import FlaskForm
from wtforms import EmailField, PasswordField, SubmitField, StringField
from wtforms.validators import DataRequired, Length

class SignUpForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(min=4, max=24)])
    email = EmailField("Email", validators=[DataRequired()])
    password = PasswordField("Password", validators=[DataRequired(), Length(min=8, max=20)])
    confirm_password = PasswordField("Confirm Password", validators=[DataRequired(), Length(min=8, max=20)])
    submit = SubmitField('Submit')

app/blueprints/auth.py
from flask import Blueprint, flash, redirect, render_template, current_app
from flask_login import login_user, login_required, logout_user, login_manager
from werkzeug.security import check_password_hash
from app.helpers.hash_password import hash_password
from app.models.user import Blog_User
from app.forms.sign_up import SignUpForm
from app.forms.login import LoginForm

auth = Blueprint("auth", __name__, template_folder="templates")


@auth.route("/sign_up", methods=["POST", "GET"])
def sign_up():
    db = current_app.extensions["sqlalchemy"]
    form = SignUpForm()
    if form.validate_on_submit():
        try:
            # check if user have an account
            check = db.session.execute(db.select(Blog_User).filter_by(email=form.email.data)).scalar()
            if check:
                flash("You already have an account!")
                return redirect(url_for("auth.sign_up"))
            # validates that the passwords are the same
            if form.password.data == form.confirm_password.data:
                username_exist = Blog_User.query.filter_by(username = form.username.data).first()
                if username_exist:
                    flash("The username is already taken")
                    return redirect(url_for("auth.sign_up"))
                try:
                    # inserting user in the database with password being hashed
                    user = Blog_User(email=form.email.data, password= hash_password(form.password.data), username=form.username.data)
                    db.session.add(user)
                    db.session.commit()
                    return redirect(url_for("auth.login"))
                except Exception as e:
                    return f"There was an error: {e}"
            else:
                flash("The passwords aren't the same, try again")
                return redirect(url_for("auth.sign_up"))
        except Exception as e:
            return f"There was an error with the signup. Error: {e}"
    return render_template("user/sign_up.html", form=form)


from flask import redirect, url_for



@auth.route("/login", methods=["POST", "GET"])
def login():
    form = LoginForm()
    # Before i was using form.populate_obj() but then the login behaves weird
    # when i was tryng to access current user what i was getting was None, so
    # i just dump it and did it manually. 
    password = form.password.data
    email = form.email.data
    if form.validate_on_submit():
        # checking if the user have an account
        user = Blog_User.query.filter_by(email = email).first()
        try:
            if user:
                # comparing password if when reverting the hash of the password
                # they are equal
                if check_password_hash(password=password,pwhash=user.password):
                    login_user(user)

                    return redirect("/")
                else:
                    flash("The password or email was incorrect.")
                    return redirect("login")
            else:
                flash("You dont have an account.")
                return redirect("login")
        except Exception as e:
            return f"There was an error with the login: {e}"
    return render_template("user/login.html", form=form)


@auth.route("/logout")
@login_required
def logout():
    # logut function for flask-login
    try:
        logout_user()
        return redirect("/")
    except Exception as e:
        return f"There was an error with the logout. Error: {e}"

app/blueprints/dashboard.py
from flask import Blueprint, render_template, redirect, url_for, abort, current_app
from flask_login import login_required, current_user
from jinja2 import TemplateNotFound
import os
from PIL import Image
from app.models.posts import Blog_Post
from werkzeug.utils import secure_filename
from ..forms.delete import DeleteForm
from app import db
from ..forms.create_post import CreatePostForm
from ..forms.edit_post import EditPostForm
from datetime import datetime, timezone

bp = Blueprint("dashboard", __name__, template_folder="templates")

@bp.route("/")
@login_required
def dashboard():
    return render_template("user/dashboard.html")


@bp.route("/view_all_posts/<int:id>")
def view_all_posts(id):
    form = DeleteForm()
    posts = Blog_Post.query.filter_by(user_id=id).all()
    return render_template("user/view_all_posts.html", posts=posts, form=form)

@bp.route("/create_post", methods=["POST", "GET"])
@login_required
def create_post():
    form = CreatePostForm()
    user_id_folder = 'user-' + current_user.get_id()
    user_folder = os.path.join(
        current_app.static_folder, 'images', user_id_folder, 'post'
        ).replace('\\', '/')


    if form.validate_on_submit():
        f = form.file.data

        filename = secure_filename(f.filename)
        image = Image.open(f.stream)
        image = image.convert("RGB")
        webp_filename = os.path.splitext(filename)[0] + ".webp"
        webp_path = os.path.join(user_folder, webp_filename)
        image.save(webp_path, format="webp", optimize=True, quality=80)
        if filename:
                #check that the 'images/post/<user>' folder exists, else it creates it 
            if not os.path.exists(user_folder):
                    os.makedirs(os.path.join(
                        user_folder
                        ))
            images = os.listdir(os.path.join(
                            user_folder
                            ))
            if webp_filename in images:
                num = 0
                filename_copy = webp_filename
                while filename_copy in images:
                    filename_copy = ""
                    num += 1
                    list_filename = filename.split(".")
                    only_name = list_filename[0]
                    only_name += f"({num})."
                    list_filename[0] = only_name
                    filename_copy = "".join(list_filename)
                
                filename = secure_filename(filename_copy)
            try:

                #built-in flask-wtf function to save images

                #charging post to database, only storing path to the image in the database
                post = Blog_Post(
                    title= form.title.data, 
                    body=form.body.data, 
                    image = webp_filename,
                    user_id = current_user.id,
                    author= current_user.username,
                    date_created=datetime.now(timezone.utc)
                    )
                db.session.add(post)
                db.session.commit()
                return redirect('/')
            except Exception as e:
                    current_app.log_exception(f'There was an error uploading the image: {e=}')
                    abort(400)
            except Exception as e:
                return f"There was an error with creating the post: {e=}"
    return render_template("posts/create_post.html", form=form)

@bp.route('edit_post/<int:id>', methods=["GET", "POST"])
@login_required
def edit_post(id):
    if current_user.username != post.author or  current_user is None:
        abort(404)
        return
    user_id_folder = 'user-' + current_user.get_id()
    user_folder = os.path.join(
        current_app.static_folder, 'images', user_id_folder, 'post'
        ).replace('\\', '/')
    post = Blog_Post.query.filter_by(id=id).first()
    form = EditPostForm(obj=post)


    if form.validate_on_submit():
        try:
            f = form.file.data
            filename = secure_filename(f.filename)
            
            if filename:
                images = os.listdir(os.path.join(
                                user_folder
                                ))
                if filename in images:
                    num = 0
                    filename_copy = filename
                    while filename_copy in images:
                        filename_copy = ""
                        num += 1
                        list_filename = filename.split(".")
                        only_name = list_filename[0]
                        only_name += f"({num})."
                        list_filename[0] = only_name
                        filename_copy = "".join(list_filename)
                    
                    filename = secure_filename(filename_copy)
                try:
            #check that the 'images/post/<user>' folder exists, else it creates it 
                    if not os.path.exists(user_folder):
                            os.makedirs(os.path.join(
                                user_folder
                                ))
                    #built-in flask-wtf function to save images
                    final_save = os.path.join(
                        user_folder, filename
                    ).replace('\\', '/')
                    f.save(final_save)
                except Exception as e:
                    return f"There was a problem saving the image while editing the post, {e=}"

                post.title = form.title.data
                post.body = form.body.data
                post.image = filename
                post.edited = datetime.now(timezone.utc)
                db.session.commit()
                return redirect(url_for('home.blog_post', id=post))
        except Exception as e:
            return f"There was an error editing the post. {e=}"
    return render_template('posts/edit_post.html', post=post, form=form)


@bp.route("/delete/<int:id>", methods=["POST", "GET"])
def delete(id):
    error = ""
    try:
        post = Blog_Post.query.filter_by(id=id).first()
        post_name = post.image
        form = DeleteForm()
        if form.validate_on_submit():
            try:
                if post_name != "test_image.png":
                    user_id_folder = 'user-' + current_user.get_id()
                    user_folder = os.path.join(
                    current_app.static_folder, 'images', user_id_folder, 'post', post_name
                    ).replace('\\', '/')
                    os.remove(user_folder)
                    print(f"Delete of {post_name} was ok")
            except Exception as e:
                 return f"There was an error deleting the image; {e=}"
            db.session.delete(post)
            db.session.commit()
            return redirect(url_for("dashboard.view_all_posts", id=current_user.id))
    except Exception as e:
        error = f"There was a problem deleting the post: {e}"

    return error

app/blueprints/home.py
from flask import Blueprint, flash, redirect, render_template, current_app, send_from_directory, request
from flask_login import login_required
from ..models.posts import Blog_Post
from sqlalchemy import desc

home_page = Blueprint("home", __name__, template_folder="templates")



@home_page.route("/", methods=['GET'])
def start():
    page = request.args.get('page', 1, type=int)  # Get the page number from the URL, default is 1
    per_page = 8  # Number of items per page

    pagination = Blog_Post.query.order_by(desc(Blog_Post.date_created)) \
                .paginate(page=page, per_page=per_page, error_out=False)
    return render_template("index.html", pagination=pagination)

# It was a function to show files in a folder. 
@home_page.route('/static/user-<user>/post/<filename>')
def show_images(user, filename):
    # print(f"{user=}")
    user_folder = f"{current_app.static_folder}/images/user-{user}/post"
    return send_from_directory(user_folder, filename)





@home_page.route("/post/<id_slug:id>")
def blog_post(id):
    db = current_app.extensions["sqlalchemy"]
    post = Blog_Post.query.filter_by(id=id).first()
    print(post.edited)
    return render_template("posts/post-view.html", post=post)

app/templates/user/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="https://imgs.search.brave.com/B0Z9vUrKJm2uhHTjOPRWqKxuci8hCc5BLYA93sjUpQE/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvNTI2/OTU2NTExL2VzL3Zl/Y3Rvci9mb25kby1h/YnN0cmFjdG8tbSVD/MyVBMWdpY28tbHV6/LXJvamEuanBnP3M9/NjEyeDYxMiZ3PTAm/az0yMCZjPXFFcUsx/MW1XX2NUMF9oZ0Ix/N0RtWURRUExVSDNP/UnFENXg2Z0lJakRJ/Zkk9">
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
    {% block head%} 
    {% endblock %}
    <link rel="stylesheet" href="{{url_for('static', filename='dashboard.css')}}">
    <title>Dashboard</title>
</head>
<body>
    <header>
        <div class="filler"></div>
        <div class="username">
            <img src="..\static\img\user_logo.svg" alt="user_logo" id="user_logo">
            <h2>
                {{current_user.username}}
            </h2>
        </div>
        <nav>
            <ul class="links">
                <li class="link-btn"><a href="{{url_for('home.start')}}">Home</a></li>
                <li class="link-btn"><a href="{{url_for('auth.logout')}}">Logout</a></li>
            </ul>
        </nav>
    </header>
    <hr>
    <main>
        <section class="actions">
            <nav>
                <ul class="links-action">
                    <li class="link-btn"><a href="{{url_for('dashboard.create_post')}}">Create Post</a></li>
                    <li class="link-btn"><a href="{{url_for('dashboard.view_all_posts', id=current_user.id)}}">View all Posts</a></li>
                </ul>
            </nav>
        </section>

        <section class="posts">
            {% block post%}
            {% endblock %}
        </section>
    </main>
</body>
</html>

app/templates/user/login.html
{% extends 'base.html' %}
    
{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='login.css')}}">
{% endblock %}
{% block title %}Login{% endblock %}

{% block body %}
    <div class="wrapper">
        <div class="background">
            <div class="form-title">
                <h2>Login</h2>
                <hr>
            </div>
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                <div class="errors">
                    {% for error in messages %}
                    <h3 class="msg">{{ error }}</h3>
                    {% endfor %}
                </div>
                {% endif %}
            {% endwith %}
            <form  method="post">
                {{ form.hidden_tag() }} 
                {{ form.email.label (class_='form-labels')}}
                {{ form.email (class_='form-inputs', placeholder="Enter your Email") }}
                {{ form.password.label (class_='form-labels')}} 
                {{ form.password (class_='form-inputs', placeholder="Enter your Password")}}

                <button type="submit" name="submit" value="Submit">
                    Submit <img src="../static/img/arrow_icon.png" alt=""></button>
            </form>
            <nav class="back">
                <h3 class="msg">Do u don't have an account? <a href="{{url_for('auth.sign_up')}}">Click here</a></h3>
            </nav>
        </div>
    </div>
{% endblock %}

app/templates/user/sign_up.html
{% extends 'base.html' %}
{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='sign_up.css')}}">
{% endblock %}
{% block title %}Sign Up{% endblock %}


{% block body %}
    <div class="wrapper">
        <div class="background">
            <div class="form-title">
                <h2>Sign Up!</h2>
                <hr>
            </div>
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                <div class="errors">
                    {% for error in messages %}
                    <h3 class="msg">{{ error }}</h3>
                    {% endfor %}
                </div>
                {% endif %}
            <form  method="post">

                {% endwith %}
                {{ form.hidden_tag() }} 
                {{ form.username.label (class_='form-labels')}}
                {{ form.username (class_='form-inputs', placeholder='Enter your Username')}}
                {{ form.email.label (class_='form-labels')}}
                {{ form.email (class_='form-inputs', placeholder="Enter your Email") }}
                {{ form.password.label (class_='form-labels')}} 
                {{ form.password (class_='form-inputs', placeholder="Enter your Password")}}
                {{ form.confirm_password.label (class_='form-labels')}}
                {{ form.confirm_password (class_='form-inputs', placeholder='Confirm your Password')}}

                <button type="submit" name="submit" value="Submit">
                    Submit <img src="../static/img/arrow_icon.png" alt=""></button>
            </form>
            <nav class="back">
                <h3 class="msg">Do u already have an account? <a href="{{url_for('auth.login')}}">Click here</a></h3>
            </nav>
        </div>
    </div>
{% endblock %}

app/templates/user/view_all_posts.html
{% extends 'user/dashboard.html' %}

{% block head %}
<link rel="stylesheet" href="{{url_for('static', filename='view_all_posts.css')}}">
{{ moment.include_moment() }}
{{ moment.locale(auto_detect=True) }}
{% endblock %}

{% block post %}
    {% if posts|length >= 1 %}
    <div class="wrapper">
        <table>
            <thead>
                <tr>
                    <th>N°</th>
                    <th>Title</th>
                    <th>Date</th>
                    <th colspan="2">Actions</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    {% for post in posts %}
                    <td >{{loop.index}}</td>
                    <td style="font-weight: 600;"><a href="{{url_for('home.blog_post', id=post)}}">{{post.title}}</a></td>
                    <td>
                        {{ moment(post.date_created).format('YYYY-MM-DD') }}
                    </td>
                    <td  class="noright">
                        <form method="post" action="{{url_for('dashboard.delete', id=post.id)}}">
                            {{ form.hidden_tag() }}
                            {{ form.delete}}
                        </form>
                        
                    </td >
                    <td class="noleft">
                        <a href="{{url_for('dashboard.edit_post', id=post.id)}}"><button>Edit</button></a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% else %}
    <div class="message">
        <h1>There was no posts found! Please make one first.</h1>
    </div>
    {% endif %}
{% endblock %}